version: "3.8"

services:
  database:
    container_name: db_api
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/db
    networks:
      - data_network
    ports:
      - 5432:5432

  dataAuth:
    container_name: db_auth
    image: postgres:latest
    volumes:
      - postgres_auth:/var/lib/postgresql/auth
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_network
    ports:
      - 5436:5432

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 4444:8080
    depends_on:
      - dataAuth
    networks:
      - keycloak_network

  api:
    container_name: ${PROJECT_NAME}_api
    image: ${PROJECT_NAME}-api-dev
    restart: unless-stopped
    build:
      context: services/api
      dockerfile: Dockerfile
    environment:
      BACK_PORT: ${BACK_PORT}
      BACK_HOST: ${BACK_HOST}
      FRONT_URL: ${FRONT_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      HASH_SALT_ROUND: ${HASH_SALT_ROUND}
      SWAGGER: ${SWAGGER}
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - "./services/api:/app"
    networks:
      - data_network
    depends_on:
      - database

  client:
    container_name: ${PROJECT_NAME}_client
    image: ${PROJECT_NAME}-client-dev
    restart: unless-stopped
    build:
      context: services/client
      dockerfile: Dockerfile
    environment:
      VITE_API: ${API}
      VITE_HOST: ${FRONT_HOST}
      VITE_PORT: ${FRONT_PORT}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - "./services/client:/app"
    depends_on:
      - api

networks:
  data_network:
    driver: bridge
  keycloak_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  postgres_auth:
    driver: local
